NF: 4
VCL: 8
apply_softmax: true
batch_size: 8
class_weights: (1., 1.)
data_mean: [.5, .5, .5]
data_path: '/mnt/experiments/sorlova/datasets/LOTVS/DADA/DADA2000'
data_std: [.5, .5, .5]
dataset: Dada
dropout: 0.3
image_shape: [720, 1280]
input_shape: [480, 640]
lr: 0.00005
pretrained: 'pretrained/swin_base_patch244_window1677_sthv2.pth'
rnn_cell_num: 3
rnn_state_size: 1024
transformer_type: 'swin_base_patch244_window1677_sthv2'
horizontal_flip_prob: 0.5
